### ISSUE TITLE
what do you mean by "AsyncIO still can't exceed the speed of GIL"

### ISSUE THREAD

**Issue by NoraGithub** [omnilib/aiomultiprocess#141]
what do you mean by "AsyncIO still can't exceed the speed of GIL", as far as I am concerned,Gil is a machinist ,not a number,so asyncio may be good enough?

**Comment by bratao** [comment]
Here have a good explanation.
https://www.youtube.com/watch?v=0kXaLh8Fz3k

The GIL don´t allow to use multiple CPU cores
