### ISSUE TITLE
Could you please post some examples for a http server

### ISSUE THREAD

**Issue by GoodManWEN** [omnilib/aiomultiprocess#22]
### Description
I'm wondering if this library helps multiple performance of a async http server like aiohttp.
Could you please give a example? 
thx.

### Details

* OS: Linux
* Python version: 3.7
* aiomultiprocess version: latest
* Can you repro on master?
* Can you repro in a clean virtualenv?

**Comment by maximdanilchenko** [comment]
I think that it could be smth like this: [aiomultiprocess-aiohttp.py](https://gist.github.com/maximdanilchenko/22ca974f0bd8b4547b1ce02d4087fc2a)

It's just a toy example and it uses some private functions from aiohttp, so be careful.
