### ISSUE TITLE
loop.map cannot work in windows

### ISSUE THREAD

**Issue by kakal** [omnilib/aiomultiprocess#44]
### Description
Hi, @jreese 
I have take a testing for example of pool.

Code as below: 
```
import asyncio
from aiohttp import request
from aiomultiprocess import Pool

async def get(url):
    async with request("GET", url) as response:
        return await response.text("utf-8")

async def main():
    urls = ["https://jreese.sh", ...]
    async with Pool() as pool:
        result = await pool.map(get, urls)

if __name__ == "__main__":
    asyncio.run(main())

```

However, I got the error message:

aio process 12492 failed
Traceback (most recent call last):
  File "C:\...\Python37\lib\multiprocessing\queues.py", line 107, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\Python37\lib\\aiomultiprocess\core.py", line 133, in run_async
    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))
  File "C:\...\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\...\Python37\lib\aiomultiprocess\pool.py", line 53, in run
    task: PoolTask = self.tx.get_nowait()
  File "...\Python37\lib\multiprocessing\queues.py", line 126, in get_nowait
    return self.get(False)
  File "...\Python37\lib\multiprocessing\queues.py", line 111, in get
    self._rlock.release()
OSError: [WinError 6] invalid handler.

I have check the code, I foud that the exception from here:

![image](https://user-images.githubusercontent.com/6667321/78763047-46ade900-79b7-11ea-8db6-0214dc27382b.png)

Line 53 and 54.

Would you please give me some suggestion?

### Details

* OS: Windows 10 , 64 bit
* Python version: 3.7.2
* aiomultiprocess version: 0.7.0
* Can you repro on master? no
* Can you repro in a clean virtualenv? yes

**Comment by jreese** [comment]
I can't reproduce this error. Tested on Windows 10 with Python 3.7.8 from python.org (using x86-64 executable installer), and a fresh virtualenv. I would suggest either upgrading to a newer release of Python 3.7, or trying with the latest version of aiomultiprocess. Cheers.
