### ISSUE TITLE
How to implement progress with Pool?

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [omnilib/aiomultiprocess#47]
### Description
I'm trying to implement a progress bar of some sort, like tqdm. Is there any way to do this with Pool? Should i use Process directly?
Thanks

### Details

* OS: linux
* Python version: 3.7.0
* aiomultiprocess version: 0.7.0

**Comment by jreese** [comment]
Currently, your best option would be to use [`Pool.apply`](https://aiomultiprocess.omnilib.dev/en/latest/api.html#aiomultiprocess.Pool.apply) to get separate futures for each item, then await those in order and keep track of your progress however you would otherwise.

I've opened #48 as a feature request to make `Pool.map` return an async-iterable, which would make this easier.

**Comment by conradogarciaberrotaran** [comment]
Thanks for the response, i'll try it out and maybe come back here with a snippet to share.

**Comment by conradogarciaberrotaran** [comment]
I failed miserably, can you point me to the right direction @jreese?
Thanks

**Comment by tarasivashchuk** [comment]
Here is how I did it and it worked: @conradogarciaberrotaran 

```
async def main(calls_list):
    pool_tasks = []
    async with aiomultiprocess.Pool() as pool:
        for call in calls_list:
            pool_tasks.append(pool.apply(get_call, args=[call]))
        [await _ for _ in tqdm(asyncio.as_completed(pool_tasks), total=len(pool_tasks))]
```

**Comment by jreese** [comment]
v0.8.0 was released with support for async iterables, which should allow you to keep track of progress as jobs are completed.  See the [user guide](https://aiomultiprocess.omnilib.dev/en/latest/guide.html) for examples.

**Comment by karolzlot** [comment]
@jreese it is not working:
(if I remove `tqdm()` then it works ok)

<img height=250 src="https://user-images.githubusercontent.com/11590960/135739642-219d4a2a-ea8b-43a6-a808-a3187ffb75db.png" />

**Comment by jreese** [comment]
> (if I remove `tqdm()` then it works ok)

I'm not familiar with tqdm, but a) it or something else would need to await the `pool.map(...)` call, and b) `pool.map` doesn't return anything until all the tasks are completed, so I don't think you would get any benefit from your use of tqdm this way. Take a look at the suggestion from @tarasivashchuk above for a way that might work better with tqdm.

**Comment by karolzlot** [comment]
I went with manual mode of tqdm, it works ok:

```
with tqdm(total=len(self.jobs)) as pbar:
                async for _ in pool.map(run_one_job, self.jobs):
                    pbar.update(1)
                   ```
