### ISSUE TITLE
Implement async iterables for map/starmap

### ISSUE THREAD

**Issue by jreese** [omnilib/aiomultiprocess#48]
### Description

Desired use case:
```python
async for result in pool.map(coro, values):
    ...
```

This could be achieved by having `Pool.map` return a special object that would either wait for everything and return all results when awaited, or when used in an `async for` loop, wait for and return each item/future in order when they're ready.

**Comment by HarsheetKakar** [comment]
Hey, I really would like to work on this issue, can I mock up a PR? I am kinda new to it.

**Comment by jreese** [comment]
@HarsheetKakar sorry, I missed your comment. I've already got an implementation for this that I'm going to include in a new release today. In the future, if there are other features or improvements, please don't hesitate to submit a PR, even if it's not "finished", and I will gladly review it and offer any guidance or assistance you need.
