### ISSUE TITLE
How to fix: " An attempt has been made to start a new process before the...." on Windows?

### ISSUE THREAD

**Issue by NotoriousRebel** [omnilib/aiomultiprocess#49]
### Description

I am facing this error and am not sure how to fix it
```

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
I tried doing multiprocessing.freeze_support() in __main__ like so:
```python
if __name__ == '__main__':
    import multiprocessing
    multiprocessing.freeze_support()
    asyncio.run(main=entry_point())
```

### Details

I recently just stumbled across this tool while trying to optimize my code, this seems like a great project!
My current problem is I keep getting this error and am unsure why, testing on wslv1 (Windows Subsystem for Linux version 1) is not feasible as the  [library](https://github.com/pyppeteer/pyppeteer) I am using seems to be broken on wslv1; however, that's a different issue. 
Here is how I am trying to use the tool 

```python
        from screenshot_class import take_screenshot, screenshot_handler, _chunk_list, receive
        unique_resolved_domains = list(sorted({url.split(':')[0]for url in full if ':' in url}))
        # Grab resolved subdomains
        # coroutines = [take_screenshot(url) for url in unique_resolved_domains]
        #await screenshot_handler(coroutines)
        async with aiomultiprocess.Pool() as pool:
            print('Created pool')
            #serialized_tiles = [take_screenshot(url) for url in unique_resolved_domains]
            #print(f'Length of serialized_tiles: {len(serialized_tiles)} ')
            #for chunk in _chunk_list(serialized_tiles, MAX_QUEUE_SIZE):
            #print(f'Chunk: {chunk} and length: {len(chunk)}')
            try:
                await pool.map(take_screenshot, unique_resolved_domains)
                #await pool.map(screenshot_handler, chunk)
            except Exception as ee:
                print(f'An excpeption has occurred while mapping: {ee}')
                #continue
```
Yes I did get inspiration from a recent [project](https://github.com/apache/incubator-sdap-ingester/blob/08093ee15346713decdc33afab23790f2aee8a76/granule_ingester/granule_ingester/pipeline/Pipeline.py#L139)

screenshot_class:

```python
import asyncio
from pyppeteer import launch


def _chunk_list(items, chunk_size):
    return [items[i:i + chunk_size] for i in range(0, len(items), chunk_size)]


async def worker(queue):
    while True:
        # Get a "work item" out of the queue.
        stor = await queue.get()
        try:
            await stor
            queue.task_done()
            # Notify the queue that the "work item" has been processed.
        except Exception:
            queue.task_done()


async def screenshot_handler(lst):
    print('Created screenshot handler')
    queue = asyncio.Queue()

    for stor_method in lst:
        # enqueue the coroutines
        queue.put_nowait(stor_method)
    # Create ten worker tasks to process the queue concurrently.
    tasks = []
    for i in range(10):
        task = asyncio.create_task(worker(queue))
        tasks.append(task)

    # Wait until the queue is fully processed.
    await queue.join()

    # Cancel our worker tasks.
    for task in tasks:
        task.cancel()
    # Wait until all worker tasks are cancelled.
    await asyncio.gather(*tasks, return_exceptions=True)


async def receive(lst):
    for url in lst:
        await take_screenshot(url)


async def take_screenshot(url):
    url = f'http://{url}' if ('http' not in url and 'https' not in url) else url
    url.replace('www.', '')
    print(f'Taking a screenshot of: {url}')
    browser = await launch(headless=True, ignoreHTTPSErrors=True, args=["--no-sandbox"])
    page = await browser.newPage()
    try:
        await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36')
        # default wait time of 30 seconds
        await page.goto(url)
        await page.screenshot({ 'path': f'{url.replace("https://", "").replace("http://", "")}.png'})
    except Exception as e:
        print(f'Exception occurred: {e} for: {url} ')
    # No matter what happens make sure browser is closed
    await browser.close()
```

There are a lot of comments as I tried a lot of different things, I am not sure if attempting to use asnycio queue + aiomultiprocess would be a wise decision. I have not been able to find examples of using queues with aiomultiprocessing so will need to watch the talk and hope it's their or give it the old scientific method. 

The big problem is my code seems to run fine then it runs the program again before spitting that issue. I tried using a Kali vm and using the fork method; however, got the same error. 
Apologies for writing an essay 😅 

* OS: Windows 10 v1909
* Python version: Python 3.7.0
* aiomultiprocess version: 0.7.0
* Can you repro on master? Yes (Cloned the repo, imported function and it crashed) 
* Can you repro in a clean virtualenv? Not sure

**Comment by jreese** [comment]
If the library you are using is trying to do its own multiprocessing, you may try to create your pool using something like:

```
async with aiomultiprocess.Pool(initializer=multiprocessing.freeze_support):
    ...
```

This will run `multiprocessing.freeze_support` after creating the asyncio event loop in the child process, though that might not be soon enough to correctly activate the freeze support. This is an unfortunate problem with specific distributions of the Python runtime on Windows, and not one that aiomultiprocess can easily work around. The best suggestion I can give is to either run on Linux or macOS, or use the official Python installer for Windows from https://python.org
