### ISSUE TITLE
[Question] Exceptions, ProxyException and Sentry

### ISSUE THREAD

**Issue by dferens** [omnilib/aiomultiprocess#80]
Hi @jreese !

I noticed that currently all exceptions in the worker processes are silenced and transferred back to master process to raise `ProxyExceptions`s. I'm looking for a way to do something with exception within the worker process, in my case - submit to Sentry. Doing this from worker process will allow Sentry SDK to capture the original exception + local variables from all frames.

Ideally I want this:
https://github.com/omnilib/aiomultiprocess/blob/main/aiomultiprocess/pool.py#L109
```python
try:
    result = future.result()
except BaseException as e:
    import sentry_sdk; sentry_sdk.capture_exception(e)
    ...
```

I propose to add API similar to [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook) into `aiomultiprocess`.
Do you have any thoughts on this? I can prepare PR.

Thanks!

**Comment by jreese** [comment]
Seems like a reasonable think to add inside the `run_async` methods of Process and Worker when dealing with uncaught exceptions, and a PR would be nice. I'd probably suggest adding something like `exception_handler: Optional[Callable[[BaseException], None]] = None` to Unit (maybe have a nicer alias for this), and plumb that through from the parent Process/Worker objects. And something similar for Pool and PoolWorker as well, if you think that makes sense.

**Comment by dferens** [comment]
Please check out my first implementation, I added the call only to `PoolWorker` as it's the single place which does not reraise captured exc. Not sure if it's actually needed to pierce all classes with this hook.
