### ISSUE TITLE
Comparison with aioprocessing

### ISSUE THREAD

**Issue by clbarnes** [omnilib/aiomultiprocess#87]
aiomultiprocess seems to have the same goals as https://github.com/dano/aioprocessing but started a few years later. Do you have any thoughts on why someone might use one over the other?

**Comment by jreese** [comment]
The two libraries are not trying to solve the same problems:

aioprocessing is an async interface to the standard multiprocessing module. It's meant for running synchronous functions on separate processes, while allowing you to queue work and receive results from an asyncio event loop.

aiomultiprocess is a framework (built on multiprocessing) for running asynchronous coroutines on separate processes, each running their own asyncio event loops, to better utilize multicore processors and increase the amount of concurrency available to asyncio.  Eg, if you can run 50 concurrent tasks per process, and have 8 cores/processes, then aiomultiprocess will allow you to have 400 concurrent tasks executing across those child processes.

**Comment by clbarnes** [comment]
Great, thanks very much for this detail! I definitely missed some subtleties there.
