### ISSUE TITLE
Github link at pypi links to aioitertools instead

### ISSUE THREAD

**Issue by rwblokzijl** [omnilib/aiomultiprocess#93]
### Description

The github link at [pypi](https://pypi.org/project/aiomultiprocess/) links to [aioitertools](https://github.com/omnilib/aioitertools) instead of [aiomultiprocess](https://github.com/omnilib/aiomultiprocess).

### Details

* OS:
* Python version:
* aiomultiprocess version: 0.9.0
* Can you repro on master?
* Can you repro in a clean virtualenv?

**Comment by jreese** [comment]
Thank you for catching this!
